### ISSUE TITLE
`flow-typed install` vs `flow-typed install package` is confusing

### ISSUE THREAD

**Issue by lydell** [flow-typed/flow-typed#1220]
`flow-typed install` (without arguments):

- Looks for packages to install in package.json 👍 
- Automatically looks for the version of each package to install in package.json 👍 
- Automatically makes a stub file if there's no definition for a package 👍 

`flow-typed install package1 package2` (_with_ arguments) _looks_ as if it would do exactly the same, but limited to just `package1` and `package2` instead of all packages in package.json. But that's not the case:

- Installs just the listed packages 👍 
- Requires you to manually go to package.json and paste in the versions in the command: `flow-typed install package1@1.2.3 package2@2.3.4` 😞 
- Does **not** make a stub file if there's no definition for a package 😞 

I found the above confusing when getting started with `flow-typed`. I was working in a project where we have _lots_ of dependencies, and I don't want to install definitions or stubs for all of them. `--ignoreDeps` unfortunately doesn't help me this case, because I want just _some_ of the regular dependencies. So I thought I could simply list all the package names I wanted in the command line: `flow-typed install package1 package2 package3 package4`. Nope. Had to manually look up all the versions. Then I manually had to run the create-stub command for every package that had no definition.

Here are some thoughts:

- Specifying a version (`package@1.2.3`) could be required only when `package` cannot be found in package.json.
- The "install-or-stub" could be a separate command. The question is what to name it, though. Or there could be a `--stubIfMissing` option to `install`.  Which could potentially be on by default when no arguments are passed, and off by default otherwise.

**Comment by stereobooster** [comment]
Woah @lydell you made my day. Didn't know about `flow-typed install` was struggling with `flow-typed install package`. Found this issue because wanted to submit report about `flow-typed install package`.

Also was wondering how this process can be improved further:

- Instead of stub we can try to convert existing TypeScript definition to Flow, with the help of [flowgen](https://github.com/joarwilk/flowgen). Yes TypeScript and Flow are not 100% compatible, but what if you are lucky enough to get compatible case and you will get type definition for free
- it would be nice to have type linting tool, which will check that there are no general types, like `any` and no uncovered types
- it would be nice to have type check tool. I think of something like quickcheck, which will use generated types to do property-based testing against actual JS code. Maybe [flow-to-gen](https://github.com/unbounce/babel-plugin-transform-flow-to-gen)?
- As soon as you generated your type stub, linted it, verified it you can submit your type signatures to `flow-typed`. It would be nice to do it with command without need to leave terminal, like `flow-typed push`. Not sure if this possible with github, but it would be nice to have, it would encourage people to share their work.

**Comment by Brianzchen** [comment]
After 4 years what you're asking for already seems the case
- running `flow-typed install react-dom` without specifying package version works unless the dependency is not listed in package.json
- we have two commands `install` and `create-stub` now. Not sure if it was there back in the day
