### ISSUE TITLE
Error with prop-types definition

### ISSUE THREAD

**Issue by tbarmann** [flow-typed/flow-typed#1283]
I just installed flow-typed on a React Native project After running flow-typed install, it installed several def files including one for prop-types library.  It is causing a linter error and I can't figure out how to fix it: 
![image](https://user-images.githubusercontent.com/249463/30885261-85696e9a-a2e0-11e7-8833-ab108d190234.png)
What am I doing wrong?
Thanks for any help.

**Comment by GAntoine** [comment]
You could

- manually change `bool`s to `boolean`s, and see if that fixes your linting issues;
- add an "ignore next line" for your linter above problem lines;
- have your linter ignore the `flow-typed` folder completely;

Since its an issue with your linter and not flow-typed, those are really the only options I can see.

**Comment by AndersDJohnson** [comment]
I get the same issue with `flow-cli@0.58.0` and `flow-typed/npm/prop-types_v15.x.x.js`.

**Comment by Brianzchen** [comment]
Agree with @GAntoine and has been documented that flow-typed dir should be eslint ignored for ease of use.
