### ISSUE TITLE
Examples of usage of lib type using markdown

### ISSUE THREAD

**Issue by sibelius** [flow-typed/flow-typed#1471]
I think we should provide a markdown (.md) of how to use the types for packages

something like DefinitelyTyped does.

Check this example: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mongoose#mongoose-methods-properties-constructors

This would help a lot newcomers to flow

**Comment by GAntoine** [comment]
I love this idea! Can't believe I've never noticed it on DT. It'll require tweaking the cli, but that shouldn't be too difficult.

**Comment by GAntoine** [comment]
Update: #1938 allows `.md` files in definition folders. **For the time being, the addition of `.md` files will not be accepted in PRs, since their presence would break certain commands.** Once the latest patch goes out, we'll give users a few weeks to upgrade to the latest patch version, then start accepting `.md` files in PRs.

**Comment by Brianzchen** [comment]
This seems to work now
