### ISSUE TITLE
koa-router_v7.2.x ctx is of any type instead of KOA Context type

### ISSUE THREAD

**Issue by gyrodave** [flow-typed/flow-typed#1698]
In type KoaRouter$Middleware the ctx type is defined as "any" when it should ideally be KOA Context type.

**Comment by saadq** [comment]
Hey there, I was the one who wrote most of the `koa-router` typedefs here. I completely agree with you, it is less than ideal putting `any` for `ctx`, however I don't know if it is possible to import types from other library definitions, which is why I left it at `any`. The alternative would be to copy/paste a ton of the type defs from `koa`.

**Comment by anonymousatc** [comment]
Hello @saadq. Thank you for your reply. I ended up importing the CTX from Koa types. I was precisely asking myself the same question : "is it possible in libdefs to import types from other dependancy libdefs"...

**Comment by saadq** [comment]
Hey @GAntoine, sorry to ping you, but just wanted to ask if you knew if it is possible or not to import type definitions from other libdefs? For example, in the `koa-router` libdef can I do something like

```js
import type { Context } from 'koa'
```

and then use that `Context` type within the `koa-router` libdef file?

**Comment by Brianzchen** [comment]
Would be solved by #1857

**Comment by Brianzchen** [comment]
This is now possible when built with the `main` branch! Example raised in PR ^ for this issues use case
