### ISSUE TITLE
react-router's <Router> history prop expect properties missing from history's BrowserHistory

### ISSUE THREAD

**Issue by esturcke** [flow-typed/flow-typed#1910]
I'm running into a problem using `react-router`s low level [`<Router>`](https://reacttraining.com/react-router/web/api/Router) component with `history`'s `BrowserHistory`. The `history` prop for  `<Router>` is expected to be a `RouterHistory` which includes `canGo`, `entries` and `index` not present in `BrowserHistory`.

```jsx
import { Router } from "react-router-dom"
import createBrowserHistory from "history/createBrowserHistory"

const history = createBrowserHistory()
const Provider = ({ children }) =>  <Router history={history}>{children}</Router>
```

This yields the following:

```
Cannot create Router element because:
 • property canGo is missing in BrowserHistory [1] but exists in RouterHistory [2] in property history.
 • property entries is missing in BrowserHistory [1] but exists in RouterHistory [2] in property history.
 • property index is missing in BrowserHistory [1] but exists in RouterHistory [2] in property history.
 • string [3] is incompatible with undefined [4] in property key of the first argument of the first argument of
   property history.block.
 • string [5] is incompatible with undefined [6] in property state of the first argument of the first argument of
   property history.block.
 • string [7] is incompatible with boolean [8] in the return value of the first argument of property history.block.
 • string [3] is incompatible with undefined [4] in property history.location.key.
 • string [5] is incompatible with undefined [6] in property history.location.state.
 • string [9] is incompatible with LocationShape [10] in the first argument of property history.push.
 • string [11] is incompatible with LocationShape [12] in the first argument of property history.replace.
 • array type [13] is incompatible with undefined [14] in the second argument of property history.replace.

          flow-typed/npm/history_v4.x.x.js
      [5]  14│     state: string,
      [3]  15│     key: string,
             :
 [11][13]  23│     replace: (path: string, Array<mixed>) => void,
             :
      [7]  29│     block: ((location: BrowserLocation, action: Action) => string) => Unblock,
      [9]  30│     push: (path: string) => void,
             :
      [1]  42│   declare export default (opts?: HistoryOpts) => BrowserHistory;

          flow-typed/npm/react-router-dom_v4.x.x.js
      [6]  44│     state?: any,
      [4]  45│     key?: string
             :
     [10]  64│     push(path: string | LocationShape, state?: any): void,
 [12][14]  65│     replace(path: string | LocationShape, state?: any): void,
             :
      [8]  71│       callback: (location: Location, action: HistoryAction) => boolean
             :
      [2] 116│     history: RouterHistory,
```

**Comment by AndrewSouthpaw** [comment]
Related at all to [this](https://github.com/flowtype/flow-typed/pull/1868)?

**Comment by txs** [comment]
I still have this issue that cannot find routerHistory from react-router

**Comment by darata** [comment]
Would something like this fix? At the top of the file import from history module

```
import type {
  BrowserHistory,
  HashHistory,
  MemoryHistory
} from 'history'
```

Then to declare the RouterHistory Type:

```
declare export type RouterHistory = BrowserHistory | HashHistory | MemoryHistory
```

**Comment by y-takey** [comment]
@darata Thank you very much! you saved my day :)

**Comment by alesn** [comment]
@darata, @y-takey  Note: Flow linter throws the following warnings when doing 
import type {
  BrowserHistory,
  HashHistory,
  MemoryHistory
} from 'history'
:
Importing a type from an untyped module makes it `any` and is not safe! Did you mean to add `// @flow` to the top of
`history`? (`untyped-type-import`)

   5| import type { BrowserHistory, HashHistory, MemoryHistory } from "history";
                    ^^^^^^^^^^^^^^
Warning --------------------------------------------------------------------------------- 

Importing a type from an untyped module makes it `any` and is not safe! Did you mean to add `// @flow` to the top of
`history`? (`untyped-type-import`)

   5| import type { BrowserHistory, HashHistory, MemoryHistory } from "history";
                                    ^^^^^^^^^^^
Warning ---------------------------------------------------------------------------------

Importing a type from an untyped module makes it `any` and is not safe! Did you mean to add `// @flow` to the top of
`history`? (`untyped-type-import`)

   5| import type { BrowserHistory, HashHistory, MemoryHistory } from "history";
                                                 ^^^^^^^^^^^^^
-----
So, BrowserHistory,  HashHistory,  MemoryHistory become typed as "any" - have type checks disabled. It is likely that the "solution" doesn't throw flow errors only because this "solution" silently disables type checks for RouterHistory (in which case it might be better to directly suppress the flow error reported in this issue with an error suppression comment, until a real resolution is in place, instead of losing type checking without knowing about it)

**Comment by darata** [comment]
@alesn I don't receive those same errors locally. I think thats because I also have the history_v4.x.x.js in my project. Is it possible for flow-typed definitions to define other flow-typed definitions as dependencies?

**Comment by alesn** [comment]
@darata [I am using the latest version of flow and flow-typed.] What I posted above are flow linter warnings. By default you will not see them, unless you configure flow to show them (these are the 'untyped-type-import' flow linter warnings). You will not see them but the problem they would report is there. 
With the latest published history_v4.x.x.js the correct way to import those three 'histories' is (so if you only need to use any of these types directly in your code and for them to be correctly typed, not silently disabling flow type checks, you can do the following):
`import type { BrowserHistory } from "history/createBrowserHistory";`
`import type { HashHistory } from "history/createHashHistory";`
`import type { MemoryHistory } from "history/createMemoryHistory";`

However, unfortunately flow-typed declarations cannot currently import other flow declarations (you would have to physically copy them over if that's feasible in a particular case), so this doesn't solve the problem in this issue

**Comment by Ashoat** [comment]
I just put up #3110, which should at least make this work without erroring:

```jsx
<Router history={history.getHistoryObject()}>
  ...
</Router>
```
