### ISSUE TITLE
New CLI command: `outdated`

### ISSUE THREAD

**Issue by micaste** [flow-typed/flow-typed#2077]
Since it is recommended [here](https://github.com/flowtype/flow-typed/wiki/FAQs#why-do-i-need-to-commit-the-libdefs-that-flow-typed-installs-for-my-project) to commit the libdef files for a project to be stable, it would be nice to have a command `flow-typed outdated` in order to detect and warn when we should update the files!

[`Yarn` has that feature](https://yarnpkg.com/en/docs/cli/outdated) and it is quite convenient.

**Comment by AndrewSouthpaw** [comment]
Sounds like a great idea, if someone wants to build it!

**Comment by Brianzchen** [comment]
I'm interested to build this and I've started a base PR to track my progress. Some questions I do have is, what exactly should we print? definitions don't necessarily have versions and the sha's between versions wouldn't be very helpful. I could just print the fact that it needs an update?

Open to feedback otherwise when I get there I'll just do something simple and leave it for future improvement

**Comment by AndrewSouthpaw** [comment]
Yeah I'd start with a simple statement of it being outdated. There's... not exactly much other information we could reasonably give.
