### ISSUE TITLE
query-string v5.1.x stringify parsed search string

### ISSUE THREAD

**Issue by mike1808** [flow-typed/flow-typed#2145]
Cannot pass the result of `parse` to `stringify`.

```js
const query = parse('?hello=world');
const search = stringify(query);
```

```
Cannot call stringify with query bound to obj because in the indexer property:
 • Either mixed [1] is incompatible with string [2].
 • Or mixed [1] is incompatible with array type [3].

        src/whatever.js
        21│
        22│ const query = parse('?hello=world');
        23│ const search = stringify(query);
        24│

        flow-typed/npm/query-string_v5.1.x.js
 [2][3] 18│     parse(input: string, options?: ParserOptions): { [name: string]: string | Array<string> },
          :
    [1] 23│     stringify(obj: { [name: string]: mixed }, options?: StringifyOptions): string,


```

**Comment by AndrewSouthpaw** [comment]
That's because of the type definitions. `#stringify` can take mixed things, e.g. `stringify({ a: 1 })` whereas the output of a parse is always string values, e.g. `parse('?a=1') ==> { a: '1' }`. So in the type definitions, while we know the output of `parse` values is string, we don't know that's the case for `stringify`. Or, another way:

Parse outputs `{ [name: string]: string | Array<string> }`
Stringify expects `{ [name: string]: mixed }`.

These are not compatible.

You might try changing stringify type to be `{ [name: string]: mixed | Array<mixed> }` and that could do it, feel free to write a test and PR.
