### ISSUE TITLE
Ramda's ifElse incompatible with test

### ISSUE THREAD

**Issue by vorobeez** [flow-typed/flow-typed#2411]
Flow throws me the folowing error:
```
Cannot call R.ifElse because rest array [1] has an unknown number of
elements, so is incompatible with tuple type [2].

     src/validator.js
       66│
       67│ const checkMaxPrecision = (maxPrecision) => R.ifElse(
       68│   R.test(new RegExp(`^\\d+\\.?\\d{0,${maxPrecision}}$`)),
       69│   R.always(undefined),
       70│   R.always(VALIDATION_ERROR.MAX_PRECISION(maxPrecision)),
       71│ );
       72│

     ../../flow-typed/npm/ramda_v0.x.x.js
 [2]   31│   declare type __CurriedFunction1<A, R, AA: A> = (...r: [AA]) => R;
         :
 [1] 1829│     cond: (...args: Array<any>) => boolean,
```

I don't understand is it error in my code or in ramda's types? How can i fix this?

Please, help.

**Comment by AndrewSouthpaw** [comment]
@LoganBarnett

**Comment by LoganBarnett** [comment]
Apologies, I must've missed the email notification for this.

@vorobeez are you still seeing this issue with a recent `ramda` libdef? We see a lot of issues relating to using rest args in the libdef and we've been working on cleaning them as we go, but there's a lot left as well.

**Comment by winghimjns** [comment]
I am having this issue as well and I have just solved it. I think there must be better way but at least the flow error is gone.

I think Ramda team didn't expect to use Ramda with Flow because in production this would never cause any typing problems.

at line 68, the type checker expects a function takes unlimited arguments and return a boolean (`(...args: Array<any>) => boolean`). But your function composed with `R.test` would output a function of `(arg: any) => boolean`.

In your case, `R.test(new RegExp(...))` returns a function accepts one arg only whilst flow thinks it should take unlimited args.

I found this is annoying as well as it should never be a problem to run. But anyway I solved it by composing a function to change the type of the original function.

So I built this:

```js
function ary<I, T>(fn: (a: I) => T): (...rest: Array<I>) => T {
    return (...rest) => fn(rest[0]);
}
```

And in your case, line 68 should exactly be changed to:

```js
   ary<boolean>(R.test(new RegExp(`^\\d+\\.?\\d{0,${maxPrecision}}$`))),
```

**Comment by LoganBarnett** [comment]
@nmn has a really good write up that explains how we can make these rest arguments work when we really need them to (like in the case of `ifElse`). I have a preliminary [try](https://flow.org/try/#0PTAEGMHsAcEsFMAmoBKBDAtotByAzqIvOADZoBOaALrJAHZ4A0oA7rFQBah4mwDmHKqAyREsAGaxw1Wg1DjI5UJ3jzYADwB0AKBCgAcpCpoARiQCeodqACueeAQAkKeGkTmA8nQsBBcpXMAHgwNJAA+eUVlDlUKPhsMeDoqPB0iUgpVcRs6cBp6K3EAURJ7QL8+PAAuUGdXRC9ffzQgkPVw5gAhZgBhMIAKbVBhiHpEGv7NKbjq0Aq8AEpQAF4Ik0hIElc6IdAFicGR+QBGCanNGZr5pdXQTt2biP7xACYz6fJKq8-FlYiex6gSYfL5zH6AzqgAA+oABoAAZLthv1DkcTu8Lj9vpUIYwkSNXhjLmCcX9YfjAcDMaDrmTITCAQBuXbpMjkLI5PKyQolMrzGp1NyNcx+ALBUKIMJdXoDfFQOjjIHnYm027rTbbPFHcSnJUg2aqiLdfGEvXUg3gsk9B5ErEk363emw5nDVmZZTmaCqAD63p6Nn8CEQADFOfk6MdyswUMwfD4rhFlmbyDUANpxgC6gJQLsIxDZqiontU-sDSFDuXDkZ80cToF9pfIQYrXPo1ejzAAVGFc272aAAG4UZQOKg1RvNsOyF6BFx8IrqaDMPBUJt0PjMdVbNB0Hss-Pu7KV7loEgsFp4QIAFQG6hqV-2QLvwglgKvvYP-aLXthAab5anegZxrO5axWes-T-SdjyAqNQNQLsuz3V1P0LYsIInACYLoYDpQQuZ4zmLpOhqTo6xRfFzhTUB0x8DMHitKCsNbCNAk6bpUDCJZESOFEqLTONiKzMkUAWZltHlFdRgVcCJF5eBUSoUd+joeAWFQeB50XfoAAMAD0AB0DMQABqIzNAAfiMxAAG8AAZGGOABfRwdIWBYtVAU9z3MPB+hyIhJFUxAPN2byL36fBIESUB4H8RQcFCsTtAk+gpPZPAbBIMdB0gWBkBhFc1z4cD5UQSLYDoaAbCoRLdDARwFy9PIini8hUoYIQMqynKBzygruFXSqSqTMr+gAVgWIA) that seems to work, so I'll try to have a pull request up to fix the issue shortly.

**Comment by LoganBarnett** [comment]
@vorobeez watch the pull request listed above, or alternatively you could pull in the libdef manually until it merges (but keep in mind it's not approved yet).

**Comment by LoganBarnett** [comment]
@vorobeez @AndrewSouthpaw @winghimjns With the merged pull request that addresses `ifElse`, I suggest we mark this issue as closed and raise a new issue if there are further problems.

**Comment by AndrewSouthpaw** [comment]
Thanks!
