### ISSUE TITLE
redux-actions handleActions: Key can be actionCreator 

### ISSUE THREAD

**Issue by Anenth** [flow-typed/flow-typed#2524]
```js
 declare function handleActions<State, Action>(
    reducers: {
      [key: string]: Reducer<State, Action> | ReducerMap<State, Action>
    },
    defaultState?: State
  ): ReduxReducer<State, Action>;
```

Over here, The input key can also be ActionCreator; according to https://redux-actions.js.org/introduction/tutorial
```js
const decrement = createAction('DECREMENT');

const reducer = handleActions(
  {
    [increment]: state => ({ ...state, counter: state.counter + 1 }),
    [decrement]: state => ({ ...state, counter: state.counter - 1 })
  },
  defaultState
);
```

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js#L111

**Comment by villesau** [comment]
@Anenth you can use

```
const decrement = createAction('DECREMENT');

const reducer = handleActions(
  {
    [increment.toString()]: state => ({ ...state, counter: state.counter + 1 }),
    [decrement.toString()]: state => ({ ...state, counter: state.counter - 1 })
  },
  defaultState
);
```

if you assign function to key, JS calls toString function behind the scenes. redux-actions has overridden the toString to return action type and that's why you can assign functions to keys. This is pretty hacky, although convenient and clever in this case. But flow does not support it, for a good reason: You very rarely want to pass function to key.

Current libdefs supports toString() and actually returns the 'DECREMENT' constant to key.

See this PR for details: https://github.com/flow-typed/flow-typed/pull/1985
