### ISSUE TITLE
Return void when parameter is void in function definition.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [flow-typed/flow-typed#2724]
[SO link if you want credit](https://stackoverflow.com/questions/52297244/flow-return-void-when-parameter-is-void)

I want to accomplish something like this:

So I'm creating some selectors, and I want the type defs to be flexible... right now I have:

```
function getName(person) {
  if (! person) {
    return undefined
  } else {
    return person.name
  }
}

const maybeFrank: ?Person = getFrank()
const definitelyMaria: Person = getMaria()

const frankName: ?string = getName(maybeFrank)
const mariaName: string = getName(definitelyMaria)
```

One possible solution is to redeclare the function type multiple times:

```
declare function getName(p: Person): string;
declare function getName(p: void): void;
function getName(p: ?Person): ?string { ... }
```

BUT you then have to tell ESLint to stop complaining and you can't use a `const` instead of `function` because Flow complains bizarrely. I'd rather not use this syntax.

Any other ideas? I tried some magic with `&` or `|` but wasn't getting the desired effect...

@LoganBarnett

**Comment by LoganBarnett** [comment]
I'd have left a comment on the SO post but I'm not reputable enough, apparently. Maybe if I walk that faction's dogs enough I'll have enough reputation points to do more? This feels like some bad games I've played ;)

I tried several permutations and couldn't get what you were looking for. One thing I want to submit to you though is that `void` isn't really composable but a true `Maybe` is. In static, functional languages I often see `Maybe` has an associated `map` used to get the value out.

Consider:
``` javascript
declare var maybeMap = <A, B: $NonMaybeType<A>, R>(B, A => R) => ?R
```

What's kind of neat about this is you can merrily chain this along and do any transformations you like. Normally we think of `map` doing some kind of traversal but really `map` just applies a transformation to the data inside of a given structure. In the case of a `Maybe`, `map` would just effect (possibly!) one "element".

Consider this totally realistic type used in a production system somewhere:

``` javascript
type Foo = {
  bar: ?Bar,
}
type Bar = {
  baz: ?Baz,
}
type Baz = {
  qux: string,
}
```

If we have a `Foo` we can chain `maybeMap` until we get to `qux`. The `qux` will still be a `Maybe` itself.

``` javascript
maybeMap(b => b.qux, maybeMap(b => b.baz, maybeMap(f => f.bar, foo)))
```

And since I know you speak Ramda, this works nicely with `pipe` and friends:

``` javascript
const maybeQux = pipe(
  maybeMap(x => x.bar),
  maybeMap(x => x.baz),
  maybeMap(x => x.qux),
)
// or
pipe(
  maybeMap(x => x.bar),
  maybeMap(x => x.baz),
  maybeMap(x => x.qux),
  actuallyDoSomethingEffectfulWithQux,
)
```

And the implication with everything here is that if the `Maybe` contains a `void`, then `maybeMap` no-ops much like `map` on a list behaves.

For the original SO post, I think this is kind of along the lines of what the other, more handsome Logan (@loganfsmyth) was getting at.

**Comment by AndrewSouthpaw** [comment]
Ha ha ha... thanks for that, Logan.

I did come up with a solution that's suiting my needs for now. It does using `Maybe` so it's chainable, that's a level of complexity/functionality I don't particularly need to worry about right now.

I answered my question in SO, here's what I did:

```js
    type FinderT<A, B, C> = (A, B) => C
    declare function maybe<B, C>(cb: FinderT<number, B, C>, id: number, other: B): C
    declare function maybe<B, C>(cb: FinderT<number, B, C>, id: ?number, other: B): void // eslint-disable-line no-redeclare
    export function maybe(cb, id, other) { // eslint-disable-line no-redeclare
      if (!id) {
        return undefined
      } else {
        return cb(id, other)
      }
    }
```

Usage:

```
    maybe(findPerson, 42, state)
```

This is limited to using an ID and one other argument, but I'll probably expand the type signature as needed. Seems to be working so far!

```js
  const foo: ?ClassroomT = maybe(getClassroom, undefined, classroomsState(state)) // ok
  const bar: ClassroomT = maybe(getClassroom, 1, classroomsState(state)) // ok
// $ExpectError
  const baz: ClassroomT = maybe(getClassroom, 1, 'foo')
// $ExpectError
  const qux: ClassroomT = maybe(getClassroom, undefined, classroomsState(state))
```
