### ISSUE TITLE
Add a check that prevents `import` statements in libdefs

### ISSUE THREAD

**Issue by NameFILIP** [flow-typed/flow-typed#2725]
Using an import from anything except `react` makes the type `any` if the type itself is not imported. See:
* https://github.com/facebook/flow/issues/6876
* https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md#dont-import-types-from-other-libdefs

**Comment by Brianzchen** [comment]
Not exactly true. react is the only third party library that can be imported because it's baked directly inside the flow builtin libs. But you can also import anything that's in the core builtins like 'fs' for node.

Flow has since made an improvements to libdefs so that it will correctly throw errors if it tries to import from a module that can't be found in the current suite.

Although this problem still exists in it's most basic form it should be solved via #1857 and implementations such as #4116
