### ISSUE TITLE
[eventemitter3_v3.x.x] unable to use ListenerFn which returns promise

### ISSUE THREAD

**Issue by ordyakov** [flow-typed/flow-typed#3242]
unable to use ListenerFn which returns not void values
it may be promise in some cases

`declare type ListenerFn = (...args: any[]) => void`

**Comment by retyui** [comment]
Fixed in: https://github.com/flow-typed/flow-typed/pull/3271

**Comment by pascalduez** [comment]
Could you provide more sample/evidence that it's a desired behaviour, looks like the promise will not be used by eventemitter. Also maybe a good first step would be to go patch [their TS definitions](https://github.com/primus/eventemitter3/blob/bb9242b0f78f04d8faae9ae06623c8003ffeedb8/index.d.ts#L54) first so that we have an "official feedback."

**Comment by retyui** [comment]
@pascalduez 
Here is the official confirmation: https://github.com/primus/eventemitter3/pull/193

**Comment by retyui** [comment]
[Try TS](https://www.typescriptlang.org/play/#src=declare%20function%20AA(fn%3A%20(...args%3A%20Array%3Cany%3E)%20%3D%3E%20void)%3A%20void%3B%0D%0A%0D%0AAA(async%20()%20%3D%3E%20%7B%20%7D)%3B%0D%0AAA(async%20()%20%3D%3E%202)%3B%0D%0AAA(()%20%3D%3E%20%7B%20%7D)%3B%0D%0AAA(()%20%3D%3E%201)%3B%0D%0A)...

**Comment by retyui** [comment]
So) ...

**Comment by retyui** [comment]
@pascalduez 
can it be closed?
