### ISSUE TITLE
@babel/code-frame_v7.x.x: Flow versions not disjoint

### ISSUE THREAD

**Issue by floriangosse** [flow-typed/flow-typed#3393]
Since #3390 was merged I'm getting the error

> @babel/code-frame_v7.x.x: Flow versions not disjoint

when I try to install my type definitions. I couldn't find anything about this error.

I'm running flow@0.101.0 and have tried to install the type definitions manually with `flow-typed install -f 0.101.0`.

**Comment by bz2** [comment]
Caused because ranges are inclusive, so these overlap `flow_v0.30.x-v0.84.x/code-frame_v7.x.x.js ` `flow_v0.84.x-/code-frame_v7.x.x.js`. Easy to fix at least @goodmind @pascalduez ?

Can't see an obvious workaround if using `flow-typed install` - and seems pretty fragile that install breaks as soon as a github master branch changes.

**Comment by uatec** [comment]
https://github.com/flow-typed/flow-typed/pull/3390/ This PR includes the overlapping flow version ranges.

Can we get this fixed or reverted?

**Comment by uatec** [comment]
Related To: https://github.com/flow-typed/flow-typed/issues/3392

**Comment by mbakowski-jsninjamaster** [comment]
Do we need just to rename folder `flow_v0.84.x-` to `flow_v0.85.x-`?

Currently there are:

- `flow_v0.30.x-v0.84.x`-
- `flow_v0.84.x-`

**Comment by pascalduez** [comment]
Fixed now

**Comment by floriangosse** [comment]
Thanks for the quick response and changes. :)

**Comment by goodmind** [comment]
wow, didn't thought that one package can break all installs
