### ISSUE TITLE
[styled-components_v4.x.x] function is incompatible with array type

### ISSUE THREAD

**Issue by kyleknighted** [flow-typed/flow-typed#3666]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
`Cannot call styled.div because function [1] is incompatible with array type [2].` error while using styled-components with prop function

**If the current behavior is a bug, please provide the steps to reproduce.**
Using the styled-components `ThemeProvider`, there is always a `theme` prop available in all styled components. Something, similar to the following example renders properly, but Flow check fails.

```js
const NewThing: React.AbstractComponent<{}> = styled.div(({ theme }) => {
  return css`
    background-color: ${theme.color.primary}
  `;
});
```

After running a flow-check, the follow error render

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/views/components/Foobar.jsx:22:58

Cannot call styled.div because function [1] is incompatible with array type [2].

     src/views/components/Foobar.jsx
      21│
 [1]  22│ const NewThing: React.AbstractComponent<{}> = styled.div(({ theme }) => {
      23│   return css`
      24│     background-color: ${theme.color.global.primary}
      25│   `;
      26│ });
      27│

     flow-typed/npm/styled-components_v4.x.x.js
 [2] 185│     [[call]]: <StyleProps, Theme>(string[], ...Interpolation<PropsWithTheme<StyleProps, Theme>>[]) => StyledComponent<StyleProps, Theme, V>;
```

**What is the expected behavior?**

This should pass flow check because it is valid styled-components behavior.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Local Environment Information**

- flow-bin `v0.109.0`
- styled-components `v4.3.2`

**Comment by omninonsense** [comment]
Small comment regarding your typing of `NewThing`, I would do something like this:

~~~js
import styled, {css, type StyledComponent} from 'styled-components';
// …
const NewThing: StyledComponent<{...}, Theme, HTMLDivElement> = styled.div(({ theme }) => {/* … */})
~~~

or to have Flow infer the instance automatically:

~~~js
import styled, {css, type StyledComponent} from 'styled-components';
// …
const NewThing: StyledComponent<{...}, Theme, *> = styled.div(({ theme }) => {/* … */})
~~~

---

This way you get type-checking _inside_ the template string literal (and the function version), and also type-checking of input props when _using_ the styled component.

**Comment by kyleknighted** [comment]
Thanks for the feedback @omninonsense - I will review this and your other feedback and see if I can come to something that works 😅

**Comment by kyleknighted** [comment]
Hey @omninonsense Ran into another one while trying to strip out props from being rendered as HTML attributes

```js
Cannot call styled(...) with function bound to strings because function [1] is incompatible with array type [2].

     58│ `;
     59│
     60│ // Stripping away the unnecessary props that render as HTML attributes
 [1] 61│ const Bar: StyledComponent<{}, {}, *> = styled(({ animated, variant, striped, value, ...rest }) => <div {...rest} />)((props) => {
```

Sorry about bugging you, just curious if you had any ideas on maybe a better way to write this one?

**Comment by omninonsense** [comment]
> Ran into another one while trying to strip out props from being rendered as HTML attributes

Is something complaining about the extra prop, or maybe a more general question would be: Why is it a problem? I'm just curious. But regarding the Flow error:

I think it's because for some reason Flow isn't picking up that the component you passed in is actually a component? :thinking: 

Does something like this work?

```js
type DivProps = {
  // Update the types, or just use `{...}` In `ComponentType`
  animated: any,
  bsStyles: any,
  striped: any
  ...
}

const Div: React.ComponentType<DivProps> = ({ animated, bsStyle, striped, value, ...rest }) =>
  <div {...rest} />

// Careful with the theme here, it's technically `void`, not `{...}`, if there
// is no `ThemeProvider` somewhere up the component hierarchy.
const Bar: StyledComponent<{...}, void, *> = styled(Div)((props) => {
  // …
}
```

I also think you might be able to achieve the same thing via a type-cast, but that would sacrifice readability, and you don't get that much terseness out of it.

P.S: Haven't tried this, _but_ I guess it should work. I'm also a bit confused though because I assumed Flow would pick up on the fact that your function should be compatible with `React.ComponentType<Props>` .

Let me know if this works or doesn't work, though. We can try something else in that case (and/or maybe fix the libdef if it can be improved).

**Comment by kyleknighted** [comment]
Thanks for the quick response! 

I used something like

```js
type BarProps = {
  animated: boolean,
  bsStyle: string,
  striped: boolean,
  value: number,
}
const BarDiv: React.ComponentType<BarProps> = ({ animated, bsStyle, striped, value, ...rest }) => <div {...rest} />;
const Bar: StyledComponent<{}, void, *> = styled(BarDiv)((props) => {
  return css` ... `;
});
```

And it still fails with the same error message.

I managed to get things working without the removal of the props - so I am good with using `const Bar: StyledComponent<BarProps, void, *> = styled.div(({ animated, striped, value }) => {` again

Thanks again for your help!

**Comment by omninonsense** [comment]
I still think like the error message is a bit confusing, but I kinda understand why it errors. Your final solution is the correct one, IMO.

The only thing is that I expected it to error because it doesn't know what the type of `animated`, `bsStyle`, `striped`, and `value` might be (and `rest` would be `{...}` I assume) since their types weren't defined previously. Oh well.
