### ISSUE TITLE
Multiple errors when running tests on react-redux

### ISSUE THREAD

**Issue by NicolasBellec** [flow-typed/flow-typed#3925]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
running tests on react-redux flow-types returns multiple errors

**If the current behavior is a bug, please provide the steps to reproduce.**

Just clone the repository and launch "npx flow-typed run-tests react-redux"

**What is the expected behavior?**
The tests should pass

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Local Environment Information**
If this issue is specific to the CLI, provide the results of running `npx envinfo` from the command line in a GitHub gist.

**Comment by Brianzchen** [comment]
It's because of suppression codes that were mandated somewhere in one of the versions in 2020. This causes every previous test to throw a bunch of errors if tests are run against them. As we maintain libraries we would also add changes to fix up all the suppression codes but there are so many test files and we haven't found a way to automate it yet so there are a lot of tests that would have this issue currently.

I suppose `react-redux` is a pretty important and useful lib. I'll see if I can put some effort to clean that one up.
