### ISSUE TITLE
Don't use yarn.lock in cli codebase

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#4019]
# Enhancement proposal
Recently we fixed a [bug](https://github.com/flow-typed/flow-typed/pull/4018) that when users installed flow-typed cli they wouldn't be able to install deps. This was caused by a [dependency](https://github.com/npm/node-semver/issues/370) that released a patched version that was incompatible with a previous version.

This should and could have been caught in tests if we didn't have a `yarn.lock` file. Which I'm proposing we remove and add a gitignore rule. The reason is, a lock file is meant to streamline between a bunch of developers on the same codebase that despite using a dependency around a certain range `^0.3.0` we will be all locked to a single explicit version `0.3.1`

For example from a random yarn.lock snippet:
```
"@samverschueren/stream-to-observable@^0.3.0":
  version "0.3.1"
  resolved "https://registry.yarnpkg.com/@samverschueren/stream-to-observable/-/stream-to-observable-0.3.1.tgz#a21117b19ee9be70c379ec1877537ef2e1c63301"
  integrity sha512-c/qwwcHyafOQuVQJj0IlBjf5yYgBI7YPJ77k4fOJYesb41jio65eaJODRUmfYKhTOFBrIZ66kgvGPlNbjuoRdQ==
  dependencies:
    any-observable "^0.3.0"
```

This works well for application projects but less so for published libraries. Because yarn.lock files are not published to npm so when a consumer installs this, all the information from a yarn.lock is useless and non-existent. So when they install `flow-typed` and the installer sees a dependency as `^0.3.0` what does it actually install? It could be `0.3.1` which matches yarn.lock or it could be `0.3.99` if that many releases have come out. In theory if we're following semantic versioning this should be non-breaking but there's always human error such as the above break from semver. 

If we have the yarn.lock removed the difference this makes is that during test runs, when it installs fresh dependencies it will always install as a consumer would, getting latest dependencies that satisfy the package.json rules, either exact or loose versions.

**Comment by lhorie** [comment]
A lockfile represents a set of dep versions that is known to work. Removing a lockfile doesn't mean that you're always installing what the user is installing; it means you're installing whatever satisfies semver at the time of installation. The distinction is important because a person A installing on monday and wednesday may in theory get different behavior than a person B who only installs once on tuesday (if, for example, some package released a regression on tuesday morning and reverted it on tuesday evening). The worst case failure mode for having no lockfile is having no repo activity for some extended period of time and then at some point, coming back to find the project completely broken without a reproducible last-known-to-be-good build.

If you want to ensure that development environment emulates a "fresh" installation, you could have a separate dev-install script or use .yarnrc to specify `--no-lockfile` (though this still suffers from the problem I outlined above).

Another alternative to ensure deps are actually at the versions you want is to vendor them (i.e. commit them into your repo and reference them by relative path). Google takes a similar approach.

**Comment by Brianzchen** [comment]
That's fair enough, I understand the limitations of the approach but have seen it used in other libs so thought it might be useful here.
