### ISSUE TITLE
Add `res` to express$Request definition in express_v4.17.x.js 

### ISSUE THREAD

**Issue by micmmakarov** [flow-typed/flow-typed#4190]
### Library definition file name

npm/express_v4.17.x.js

### Your dependent version

4.17.x

### Flow Version

0.133.0

### Description

I'd like to add `res` to Request definition in https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/express_v4.17.x/flow_v0.104.x-/express_v4.17.x.js#L51.

1. The def already exists in typescript defs: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-serve-static-core/index.d.ts#L648
2. This is where `res` it's being assigned in express https://github.com/expressjs/express/blob/master/lib/middleware/init.js#L28
3. Docs added to expressjs recently: https://github.com/expressjs/expressjs.com/pull/1291

Now I have to have my own intersection type override to fix it, but if approved, I'll send a PR.

### Do you want to submit a pull request to fix this issue?

Yes

**Comment by Brianzchen** [comment]
Hey thanks for raising this issue, since you want to work on this PR yourself here are some tips to get started.

- This is the file you want to work on https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/express_v4.17.x/flow_v0.104.x-/express_v4.17.x.js
- Usually we expect a test, it would be nice if you did so too but your change is fairly minor I personally wouldn't mind
- [here](https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md) is the contributing guide, let me know if anything doesn't work here
- When you run your tests your going to get a lot of `$FlowExpectedError` test failures requiring suppression codes, I'll see if I can fix that quickly for you but if you cause any additional extra test failures you'll have to fix that before merging
