### ISSUE TITLE
RXJS v6.6.7

### ISSUE THREAD

**Issue by fedgrant** [flow-typed/flow-typed#4307]
### Library definition file name

rxjs_v6.x.x.js

### Your dependent version

6.6.7

### Flow Version

0.142.0

### Description

I believe there is a duplicate type
```
declare export function multicast<T>(
    subjectOrSubjectFactory: rxjs$FactoryOrValue<rxjs$Subject<T>>
): rxjs$UnaryFunction<rxjs$Observable<T>, rxjs$ConnectableObservable<T>>;
  
declare type rxjs$FactoryOrValue<T> = T | (() => T);
```

```
declare export function multicast<T>(
    rxjs$SubjectFactory: () => rxjs$Subject<T>
): rxjs$UnaryFunction<rxjs$Observable<T>, rxjs$ConnectableObservable<T>>;
```

link for reference [  declare export function multicast<T>(](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/rxjs_v6.x.x/flow_v0.104.x-/rxjs_v6.x.x.js#L2525)

### Do you want to submit a pull request to fix this issue?

Yes

**Comment by fedgrant** [comment]
I can submit a PR if this is actually a bug, I'm not 100% that it is.

**Comment by Brianzchen** [comment]
Hey thanks for your submission, though I'm not super familiar with rxjs I believe the duplicates are overloaded methods for the same function so that they can be used in a multitude of ways. Or are you suggesting that one/some of these definitions are exactly the same and therefore we should clean some of them up? 

### Screenshot of overload in action
<img width="960" alt="Screen Shot 2022-04-29 at 7 24 41 am" src="https://user-images.githubusercontent.com/12436524/165848436-e0a9743e-2da6-49a5-aa56-b35633a4aa18.png">

**Comment by fedgrant** [comment]
I think they are the same.

`rxjs$FactoryOrValue<rxjs$Subject<T>>` would be  `rxjs$Subject<T> | (() => rxjs$Subject<T>);`

which is the same as `() => rxjs$Subject<T>` in the second case

**Comment by Brianzchen** [comment]
Yes as I keep staring at this they are the same as far as I can tell. I'm ok if you'd like to remove them. As long as tests continue to pass which I imagine they should it's no trouble with me
