### ISSUE TITLE
[QUESTION] I'm a bit confused about new libdef creation process

### ISSUE THREAD

**Issue by ItsAleph** [flow-typed/flow-typed#4332]
Am I right that when I need to make a libdef of a library that has TypeScript definitions, I need to look at each export of the library and port export's TypeScript definition to the Flow defenition?

**Comment by Brianzchen** [comment]
More or less, their syntaxes are similar but not the same, generally in the areas of how they declare the package modules are different.

While a TS module can just write `export const blah` every definition for flow-typed must be wrapped in 

```
declare module 'blah' {
 // ...
}
```

I'm not pro at TS but my general assumption is just that they have a looser syntax in general. TS also tends to have namespace's while flow doesn't so that also requires manual work

You can use tools out there that convert ts to flow but I've seen very little success of people doing that over the years and it usually just becomes abandoned because they don't want to overwrite the work their tool already put in.

**Comment by ItsAleph** [comment]
Thanks! Also, I think it might be good to make an issue template for general questions instead of manually assigning the question label

**Comment by Brianzchen** [comment]
You're welcome and appreciate that feedback I'll look into it!
