### ISSUE TITLE
failing to recognize null/undefined check in function

### ISSUE THREAD

**Issue by ridakk** [flow-typed/flow-typed#4356]
### Library definition file name

lodash_v4.x.x.js

### Your dependent version

4.17.15

### Flow Version

0.183.0

### Description

failing to recognize null/undefined check in function.

```
  const { isNil } = require('lodash');

  const obj = null;

  if (isNil(obj)) {
    console.log(obj);
  } else {
    console.log(obj.a); -> Cannot get `obj.a` because property `a` is missing in  null [1].Flow(incompatible-use)
  }
```

### Do you want to submit a pull request to fix this issue?

No (hope someone else can)

**Comment by Brianzchen** [comment]
Hi there, so based on what you've provided so far I don't think this is possible. This is mainly a limitation of flow with library definitions.

Generally if `isNil` was more than just a definition and was actually typed you'd use [flow predicate functions](https://flow.org/en/docs/types/functions/#toc-predicate-functions) which contains logic on why something is `Nil` and flow can run a [type refinement](https://flow.org/en/docs/lang/refinements/) on the value you pass in, but because it's just a definition there's no logic to parse.

What you have here though is `isNil(obj)` which lets assume that `obj = null` in this case. Then flow for sure can parse that and be absolutely sure that `isNil` should be `true` since the definition states `(value: void | null) => true`.

But the problem is that flow does not know the inner workings of the function when written in JS so how does it know that just because `isNil` produced `true` that `obj` is `null`? There's no logical relationship between them from flow's eyes.

I think `isNil` is useful but it'd mostly be to compute some value to `true / false` and then using that value for other logic instead of using it as a type refinement. In this case I think you'd be better off using `typeof` or `obj == null` which whether it's `undefined` or `null` would result in `true` which type refines your situation.

Maybe this will suit you better? Happy to try help more if not

```
  const obj = null;

  if (obj == null) {
    console.log(obj);
  } else {
    console.log(obj.a); -> Cannot get `obj.a` because property `a` is missing in  null [1].Flow(incompatible-use)
  }
```

**Comment by ridakk** [comment]
guess it is better to replace lodash.isNil with a native implementation as below; 

```
const isNil = (value: ?any): boolean %checks => {
  return value == null;
};
```

**Comment by Brianzchen** [comment]
yeah if you need it reusable that's one way to go about it too :)
