### ISSUE TITLE
Consider separating CLI.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [flow-typed/flow-typed#526]
Something like `flow-typed` and `flow-typed-cli`.
This would expose the API and make it easier to test.

**Comment by ryyppy** [comment]
Hey! I see you are really motivated to get this thing going, but I am not in charge for major decisions... I am also a little bit lost here, since I don't know what the flow team is cooking :-)

Since there is no huge benefit (and since every maintainer is used to this repo design), we will keep it like that for now.

If you feel confident in contributing, I could offer you to try #104, since this task would bring a lot of value :-)

**Comment by wtgtybhertgeghgtwtg** [comment]
One of the reasons I would advise this is to incentivise testing and documentation.  The lack of tests is holding up #490; to write tests, I would either have to expose the API anyway, or test the CLI.  The lack of documentation is forcing the `create-react-app` team to use `flow-typed` in [a very round-about way](https://github.com/facebookincubator/create-react-app/pull/1152#discussion_r91699203).

**Comment by ryyppy** [comment]
Okay got ya... maybe let's continue discussion on the `create-react-app` issue

**Comment by rricard** [comment]
@ryyppy the discussion is pretty long already and this sub-discussion is not central to the feature I'm integrating. We don't need clear CLI separation but that'll be surely a nice to have in the long term. I don't want you to rush a design decision on this. Take your time, when available and documented, we'll reintegrate that into CRA.

**Comment by jeffmo** [comment]
I've been thinking about this a bit myself as well and I think it might make sense. I'll look into what it will take to split into another repo

**Comment by wtgtybhertgeghgtwtg** [comment]
Would you like a PR making `flow-typed` a `lerna` monorepo?  Then you could separate it into `flow-typed` and `flow-typed-cli` or something.
