### ISSUE TITLE
JSONAPI Types

### ISSUE THREAD

**Issue by krainboltgreene** [flow-typed/flow-typed#693]
So I'm new to flowtype and I'm not quite sure how contributing works, but I recently wrote a jsonapi.org typeset:

``` javascript
type JSONAPILinkType = {
  href: string | Array<string>,
  meta?: Object
}
type JSONAPILinksType = {
  [name: string]: string | JSONAPILinkType
}
type JSONAPIRelationType = {
  id: string,
  type: string,
  links?: JSONAPILinksType,
}
type JSONAPIRelationshipsType = {
  [relationship: string]: JSONAPIRelationType
}
type JSONAPIRResourceType = {
  id?: string,
  type: string,
  attributes: Object,
  relationships?: JSONAPIRelationshipsType,
  links?: JSONAPILinksType,
}
type JSONAPIDataType = JSONAPIResourceType | Array<JSONAPIResourceType>
type JSONAPIIncludedType = Array<JSONAPIRResourceType>
type JSONAPIRootType = {
  data: JSONAPIDataType,
  meta?: Object,
  included?: JSONAPIIncludedType,
}
```

**Comment by infiniteluke** [comment]
Small typo: `JSONAPIRResourceType` should be `JSONAPIResourceType`

**Comment by egeriis** [comment]
Are there any examples of libdefs that are not coupled w/a library, but only contains type definitions?

**Comment by AndrewSouthpaw** [comment]
You could probably put it in `browser` and then try importing the types from the module:

```js
// json-api.js
declare module 'json-api' {
  ...
}

// my_foo.js
import type { JSONAPIRootType } from 'json-api'
...
```

Try that out and see if it works.

**Comment by zeorin** [comment]
Jest's type definitions add global definitions for the things that Jests injects into the global scope in test files, so you can have a look at that.

Incidentally, I also created my own libdef for JSON:API (before I found this issue), I think it's more complete than @krainboltgreene's. I've also tested it against all of the examples I could find on http://jsonapi.org/.

```js
type JSON =
	| null
	| void
	| string
	| number
	| boolean
	| { [string]: JSON }
	| Array<JSON>;

type JSONAPIMeta = { [string]: JSON };

type JSONAPILink =
	| string
	| {|
			href: string,
			meta?: JSONAPIMeta,
	  |};

type JSONAPILinks = {
	self?: JSONAPILink,
	related?: JSONAPILink,
	[string]: JSONAPILink,
};

type JSONAPIPaginationLinks = {
	first?: ?JSONAPILink,
	last?: ?JSONAPILink,
	prev?: ?JSONAPILink,
	next?: ?JSONAPILink,
};

type JSONAPIError = {|
	id?: string,
	links?: {|
		about: JSONAPILink,
	|},
	status?: string,
	code?: string,
	title?: string,
	detail?: string,
	source?: {
		pointer?: string,
		parameter?: string,
	},
	meta?: JSONAPIMeta,
|};

type JSONAPIObject = {|
	version?: string,
	meta?: JSONAPIMeta,
|};

type JSONAPIAttributes = {
	[string]: JSON,
};

type JSONAPIResourceIdentifier = {|
	id: string,
	type: string,
	meta?: JSONAPIMeta,
|};

type JSONAPIResourceLinkage =
	| Array<JSONAPIResourceIdentifier>
	| JSONAPIResourceIdentifier
	| null;

type JSONAPIRelationship = {|
	links?: {
		self?: JSONAPILink,
		related?: JSONAPILink,
	} & JSONAPILinks,
	data?: JSONAPIResourceLinkage,
	meta?: JSONAPIMeta,
|};

type JSONAPIRelationships = {
	[string]: JSONAPIRelationship,
};

type JSONAPIResource = {|
	id?: string,
	type: string,
	attributes?: JSONAPIAttributes,
	relationships?: JSONAPIRelationships,
	links?: JSONAPILinks,
	meta?: JSONAPIMeta,
|};

type JSONAPIDataDocument = {|
	data:
		| Array<JSONAPIResource | JSONAPIResourceIdentifier>
		| JSONAPIResource
		| JSONAPIResourceIdentifier
		| null,
	meta?: JSONAPIMeta,
	jsonapi?: JSONAPIObject,
	links?: JSONAPIPaginationLinks & JSONAPILinks,
	included?: Array<JSONAPIResource>,
|};

type JSONAPIMetaDocument = {|
	meta: JSONAPIMeta,
	jsonapi?: JSONAPIObject,
	links?: JSONAPILinks,
|};

type JSONAPIErrorDocument = {|
	errors: Array<JSONAPIError>,
	meta?: JSONAPIMeta,
	jsonapi?: JSONAPIObject,
	links?: JSONAPILinks,
|};

type JSONAPIDocument =
	| JSONAPIDataDocument
	| JSONAPIMetaDocument
	| JSONAPIErrorDocument;
```
[Flow try](https://flow.org/try/#0C4TwDgpgBAUgygeQHJQLwCgCQAfKA7AVwBsitcA3AewEsATMqAZ2ACdq8BzBwgWwCMILBn0qUiEAIZ4GAbygBtZm04BdAFyxEKAL4MAgixYSQAHnjIAfAG506UJE3I9ABQCSAWQjAJaKHMWs7Bzqjjo2duDQ5kgurgAy7ADWaAxKQbLYWJiYABYsEABmGmmcADRZmDxeEgD8GtGxnt7lmFBQ2Nrh9lFasQl4iYy+MliMEEQFdaF9SS35RBLAELRTDW79iS0BysH1veuz6J223dNuzhIc7IvUlHgbQ6h+WAXULMxTNWvxh5gLHxovvsfgMWmB8uRPt8Ni08BAAB7AKHAmFHLqRM6uACihkoLGGmUwdCmJQ4LSISUYUxkhMwEhEBGAeycB1BZG0LWYiwIVOKgTKWAAxpRaBASfyyVhgNRgOJxTsWqLvNQiPKgpzKAQWIKxRoRtkwDQ8EsWGqBQaJEYqiazZLMBysNbasyYm4mhJyh10Q5vgg+AArCCC4AErDkQSMW54W0tJ2rYHuz3HCI+4F6YCBPiMiCPZ6YbZBELRcrJ07fABKOc12ogrlFxuor0EoaJtD5CqlkXb6sd1XjLI81ST3p6A8rjGrOo2l2gGBwUAMRlMFarWp1dYgDabLAsDBXE7Xtfr0u33GIRBHmMrC2ld0YOWoYBbFIGvLzmDGE37rpBmyy80WZZvxmNl7SgAAyTEHkVRZnSvVca2nDgIFjPsXUaId0C9E4MRXG8o3vR9c31AtVHQtxrxuO8HzAEtL33SdZz8QliW7c1ujYu1FkzbM32+dMeKWRg5nGKi8EIsA+OBSjb3EmjhKwF9BmA1lBlQ7wVMHZosNLXDgQAEVg-TKEFAgqmNFtaFgtQslwRdjDMaSEJ1dp4IPGsNy3ahBF3bJcAYw9bLcxjPJPbyhD8-Bz3UuDvkTLB-QnPAJDAahNL9QNg3JSlNIuK5ktkh4IKgykWnYQUiAIUUVg0ezlyc9ydQsYccNTAd3WM0zzJDJ4aV7bxyK0j0EqSlK0sGjKg2AbLX006CdPo4EcRYPFOrMzceuYrBBBW95asMBzvmWvFmv62KE0wzBEruMb0oDKaZuUwb5uwlNRx-NbupSedvkM7xPo2vcLv+kz1uNIGB2OlgAeNcIAAp9SsgaFCyfVsg4qAAHJLWlCqc0xlpsjoDRMYARgJipuLYLMhL1CpMGlWUIBJ6IFzcKAwAkdhgCGHgQCgPhqESHMcmWABCCnsntQm-kpOmpY-cYiixnIMzANQAHoNYRCQeDAcQADphR4DWceoPHGA18mZYdKWANkiTGHlqWJEZHI8WdqWlKd98Fc-ZXMdV4B1a1nW9cN43TZYXHxEt0mNftgj5NNt28UlhXMHt5YSaDkPtfhXX9YgI3KBNs2LatlPgHdlh06l22FaRiQ9SgDHMcgSgi4JqBiaxgBOTGoAb7Jh8wY3up9tGvbl32pf9nO1c1-PC4j0uo5jnNK8T6iiI18eNsYOu7dEpY2xVxfQ4L8Pi8j8vY8r-fjUPmWR5fzAm40eR6eyOQ28fnnu690xgAVkHqPH+rcuxY3-s-HuZ8yYACYwFvxUC-YeDdbaoKwOVSq1VP6owqG3DuXcZZAIHjLKm1AaY5k9pgTGrx3jAAALTJSqJjEmhk8BH0xv8ZhrCIDsKxgAcQgHwHIlpaDACPsAAA7jKE0JNaDIT4HXYe3taHz3PsHJeYci4lxNsQ8QGtyEVAwYTKef9S4TzrkA0BFCMzU14rQkQtAQAkwAGJvGYBLG2Mtt5ySIrQ121cPaz3ftZPwkDIAk0MQI0ocCSZIKHmg3xFR1Gz00YHC+y9r76L3lYg+Gs7GmMJg3CxUDMYwJsfA0mSD7GCRobPFxbisauCgBSYWUAAAa7g4gCy8CaVRfiT5J0CbPYJNdaHhORr-CpsTAHwIHsk+m6CZbpKnorCYC9tGXxXjfNeMCrZ1JKVkTBJZBow2AAASnhvqJ0zthRgBAGwDgqsSYAGFO7POoK8kMCCAAMpNgFQCxFfIuUBPksDAAbdOEy8Q+3kJjAAmhAHIVUfAAGlFgAC9u6YzgEscMUAMULD4HgIWeLOFQBEWIiRUj4mYwACogHEPiDF4xxBcKwdLLAH93xtzvvjQmQDrZZEodQyehCZTiBJuWLmRAhjUCGAgHgEhEgSDGOnBu6yKiZNzjosFq8y7R3NvfUVr8sAOm0Bc0G3Ubm2ARiNG6qUW7hneFGEmpMDb-OQdtXEe0UY-wqMKUUnqEEAGY66NWZpEw03NBAkw1k3U2DiqG8Q1gw5gLDdYCOWVLRmMqsYADUJCVWgEq1uogmA13pRUJU8qPFeJDPwqAPAeQhmFMaLmeAoCLHaZIZgrc8gQGgIKcRRhgwRhhaU8xwaRQxsxgghBxS56MRbnG40CasZJtgimhpltOaMEYDIvEtBfX5ulczemmMLhHpPSwWgvN21QE7cqHtPhxAZkEPE3gAgWDxKkLQDmBA8DBgIGJF946JCTpYNOut1QVQk0ZaLDmGrj2no5itcgdBlg915kqyMnBe3AdA8AcDslIOWmgyaODFqg1SxDQupdAA2KNa7Y1GgUdu5N4r02HvQw+896NL0k1vQJoDgHUN3ow52hhqqKO0EoPgSgIZ5NjtozyzAWDrWYkuTcoAA) (includes the type assertions of some of the examples, including all of them crashes the tab).

I guess, while we're at it, should we create a type definition for plain JSON (perhaps handle that in a separate issue)? I had to create one so that I could create these type defs. There's an issue open at the Flow repo about it already: https://github.com/facebook/flow/issues/4825, but perhaps it's better here.

I created the types primarily to be able to type check a generic JSON:API document. The types could be expanded by creating utility types for more specific JSON:API documents that allow a smaller subset of the generic document (e.g. a PATCH request has restrictions on the structure of the top-level `data` member, so a `JSONAPIPatchRequestDocument` type might be useful for some).

I'd be happy to create a PR, if we have consensus on whether we'd like to have global types for this, like Jest (although there's some resistance to that idea even for Jest: https://github.com/flow-typed/flow-typed/issues/251), or just import the types we want instead.

Also, although we could put the types in `browser`, they may also be useful on the server-side. I'm not sure what the actual impact of putting them in `browser` is, but certainly the location would be misleading.

**Comment by AndrewSouthpaw** [comment]
Yeah go ahead and create a PR. I'd say make it such that they must be imported. I don't want global types, @GAntoine can weigh in as well.

Yes, `browser` is misleading. It's for any thing that doesn't exist within npm. We could change the name to `non-npm` or something like that.

**Comment by egeriis** [comment]
Awesome work @zeorin !

**Comment by egeriis** [comment]
Small update. Took a bit more effort than anticipated, so I didn't get above done as fast as I anticipated. Will post the link to my WIP once I get to the computer I made it on. History doesn't move with new computers 😉 😱

**Comment by egeriis** [comment]
I completely forgot about this 😳

I've got something to share, will post this week.

**Comment by AndrewSouthpaw** [comment]
Sounds good.

**Comment by zeorin** [comment]
@egeriis ping… :smiley:

I've just discovered that my types above can lead to a really slow Flow experience, probably related to https://github.com/facebook/flow/issues/5631. I'd love to dig in and refactor but I'm on a deadline at the moment and don't have the time.

**Comment by yotam707** [comment]
Anyone has any update?

**Comment by Brianzchen** [comment]
implementing the types seems interesting, if anyone really wants this we've actually since implemented [environment definitions](https://flow-typed.github.io/flow-typed/#/env-definitions) which suits the **non-library** definition use case.

Feel free to raise a PR for the types, otherwise I'll add this eventually...
