### ISSUE TITLE
Improve flow-typed and eslint compatibility

### ISSUE THREAD

**Issue by jpolo** [flow-typed/flow-typed#779]
After installation of flow-typed in a project in the `/flow-typed` folder there are often style conflicts with .eslintrc rules at the root of the project.
It is normal because the definitions are defined with a style that comes from the github repository.

There are many possible solutions : 
* Ask ESLint to ignore 'flow-typed' folder by default
* `flow-typed install` can configure `.eslintignore` to ignore flow-typed folder
* `flow-typed install` can create a `.eslintrc` in the flow-typed directory that disable all rules (root=true and empty rules)

**Comment by captainkovalsky** [comment]
@jpolo Also eslint doesn't check the flow-typed directory so eslint unable to track that type can be imported from flow-typed/<stub> and causes import/named error

**Comment by watadarkstar** [comment]
This: "eslint unable to track that type can be imported from flow-typed/ and causes import/named error".

**Comment by Brianzchen** [comment]
I'm very interested in this. Every project I setup needs to disable eslint in `flow-typed` We might as well make `flow-typed` apply this automatically but it's much cleaner to add an `eslintrc` in `flow-typed` directly instead of mutating `.eslintignore`. 

Does anyone know to add an eslintrc at a folder level that will completely disable all rules in it's dir and children? Otherwise I'll figure it out myself later.

**Comment by Brianzchen** [comment]
Just figured it out. We can add `.eslintrc.js` into `flow-typed/npm` with these contents and it will turn off linting
```
module.exports = {
  ignorePatterns: ['**/*.js'],
};
```

**Comment by Brianzchen** [comment]
Added docs for how to handle eslint errors from flow-typed
https://flow-typed.github.io/flow-typed/#/faq?id=my-flow-typednpm-dir-is-throwing-lots-of-eslint-errors-after-installing-definitions
